### ISSUE TITLE
Problem with latest versions

### ISSUE THREAD

**Issue by locks** [AdamAtomic/HelloWorld#1]
I'll try to be terse.

flixel: 2.32
flex: 4
os: OSX 10.6

compiling this example with mxmlc doesn't give any errors, but it doesn't load the text.
it doesn't even bring up the pause menu if I switch focus.

the 'fix' is adding the preloader. I don't understand why, can you explain please?

Thanks in advance :)

[edit]  
following error in flash player 10 debug:
    ReferenceError: Error #1065: Variable HelloWorld is not defined.

**Comment by mkmgames** [comment]
I have the same problem, too.
My OS is Ubuntu 10.10
